apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: LoadBalancer  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
